<?php

/**
 * Implements hook_theme_suggestions_block_alter().
 *
 * As per https://www.drupal.org/docs/8/theming-drupal-8/creating-a-drupal-8-sub-theme-or-sub-theme-of-sub-theme
 * to ensure that sub themes inherit block templates.
 */
function dta_gov_au_theme_suggestions_block_alter(&$suggestions, $variables) {
  foreach ($suggestions as &$suggestion) {
    $suggestion = str_replace('dta_uikit_base_', 'dta_gov_au_', $suggestion);
  }
}
